### PR TITLE
Revert "add download button and functionality"

### PR DESCRIPTION
**Pull request by TharVid**
Reverts TharVid/Open-Source-Badge-Generator#8

### CODE REVIEW

**Review by TharVid — COMMENTED** [review]
Hey, @hhelenxu  it's not working! Can you please test it on the live Github page with your forked repository and create a PR again.

**Comment by hhelenxu** [comment]
Hi I'm sorry I just saw this. Is the issue fixed?

**Comment by TharVid** [comment]
@hhelenxu  Yea, Thank you! I merged your PR after some edits.

**Comment by hhelenxu** [comment]
Got it! What was the issue?

**Pull request closed without merging**
