### PR TITLE
Add a share on twitter button #hacktoberfest

### PR DESCRIPTION
**Pull request by yhau1989**
Add a share on twitter button in same style. #33 #hacktoberfest

### CODE REVIEW

**Comment by TharVid** [comment]
@yhau1989  Please make sure your edits are not conflicting with other files. I request you to update and commit again.

**Comment by yhau1989** [comment]
@TharVid  Done 👍

**Comment by yhau1989** [comment]
Screen Shot 2020-10-20 at 01 15 25 good look

**Comment by TharVid** [comment]
@yhau1989  Great Job.

**Pull request merged**
